### ISSUE TITLE
Invalid broker address

### ISSUE THREAD

**Issue by johnny5th** [adafruit/Adafruit_CircuitPython_MiniMQTT#50]
I've been playing with the Adafruit Matrix Portal to display some data from an AWS MQTT broker, and I've been running into an intermittent issue. After some period of time, it can be over 30 minutes or more, MiniMQTT throws an exception in the reconnect loop and dies, and I can't figure out why. Resetting the board makes it work again. Using libraries from adafruit-circuitpython-bundle-6.x-mpy-20201029.

[code.txt](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/files/5466402/code.txt)

Failed to get data, retrying
 Failed to send 2 bytes (sent 0)
Traceback (most recent call last):
  File "code.py", line 159, in <module>
  File "code.py", line 158, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 675, in reconnect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 292, in connect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 292, in connect
MMQTTException: ('Invalid broker address defined.', RuntimeError('Expected 01 but got 00',))

**Comment by ladyada** [comment]
try the very latest release of esp32spi library - we just fixed a few bugs!

**Comment by johnny5th** [comment]
Thanks ladyada! I swapped the lib out and am letting it run.

**Comment by brentru** [comment]
@johnny5th  Any update? Still having the same error or is it fixed?

**Comment by johnny5th** [comment]
All Fixed! It's been running for 12 hours straight now. Thanks again!
